import "./globals.css";
import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark bg-slate-1 text-slate-12 flex min-h-screen">
        <div className="w-full px-4 container flex flex-col">
          <Theme>{children}</Theme>
        </div>
      </body>
    </html>
  );
}
